[project]
name = "dj-llm"
version = "0.1.0"
description = "Fine-tuning multimodal LLMs to be world-class DJs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio-client>=1.13.3",
    "mutagen>=1.47.0",
    "pygame>=2.6.1",
    "textual>=6.4.0",
]
